version: '3'
services:
  student_service:
    image: dwolfv/student_service
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
    ports:
      - "8080:8080"

  mongo:
    restart: always
    image: mongo:5.0.11
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    networks:
      - mongo-network
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "9081:8081"
    networks:
      - mongo-network

networks:
  mongo-network:

volumes:
  mongodb_data:
